django_school/django_school/urls.py
from django.contrib import admin
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from core import views
from api import views as api_views
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic.base import TemplateView
from rest_framework.routers import SimpleRouter
from rest_framework.authtoken.views import obtain_auth_token

# Creating simple router and api path
router = SimpleRouter()
router.register('teachers', api_views.TeacherView)
router.register('students', api_views.StudentView)
router.register('groups', api_views.GroupView)


urlpatterns = [
    # django urls
    path('admin/', admin.site.urls),
    # main urls
    path('', views.GroupView.as_view(), name="index"),
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('teachers/', views.TeacherView.as_view(), name="teachers"),
    path('add/group/', views.AddGroupView.as_view(), name="add_group"),
    path('add/student/', views.AddStudentView.as_view(), name="add_student"),
    path('update/group/<int:pk>/', views.UpdateGroupView.as_view(), name="update_group"),
    path('update/student/<int:pk>/', views.UpdateStudentView.as_view(), name="update_student"),
    path('contact_us/', views.ContactUsView.as_view(), name='contact_us'),
    path('contact_us/done/', TemplateView.as_view(template_name="contact_us_done.html"), name="contact_us_done"),
    # download and test urls:
    path('download/students/', views.ExportStudentsCSV.as_view(), name='download_students'),
    path('test/', views.TestView.as_view(), name="test"),
    # Api urls:
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include(router.urls)),
    path('api-token-auth/', obtain_auth_token, name='api-token-auth'),
    # debug + static
    path('__debug__/', include(debug_toolbar.urls)),
] + static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT
) + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

django_school/core/models.py
from django.db import models  # for making Class(tables) in DB
from django.db.models.aggregates import Count, Avg, Max, Min
from django.core.mail import send_mail
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.contrib.auth import get_user_model
from core.tasks import send_contact_us_email


# Class for AbstractUser:
# class MyNewUser(AbstractUser):
#     """
#     When we inherit from AbstractUSer class we got almost same user as we got before.
#     And we can making new fields for user
#     """
#     phone = models.CharField(max_length=15, blank=True, null=True)
#     age = models.IntegerField(blank=True, null=True)


# GroupManager for aggregating Group Model with Student Model:
# class GroupManager(models.Manager):
#
#     def group_student_age_count(self):
#         return self.get_queryset().annotate(stq=Count('student'), stavg=Avg('student__age'),
#         stmax=Max('student__age'), stmin=Min('student__age'))


# Create Group Model:
class Group(models.Model):
    course = models.CharField(max_length=255)
    group_lead = models.ManyToManyField('core.Teacher', blank=True)

    def __str__(self):
        return self.course

    # objects = GroupManager()


# Create Teacher Group Model:
class Teacher(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField(max_length=40)

    class Meta:
        unique_together = ('name', 'email')

    def __str__(self):
        return self.name


# Create Student model:
class Student(models.Model):

    GENDER_MALE = 1
    GENDER_FEMALE = 2
    GENDER_ALIEN = 3
    GENDER_FICTIONAL_CHARACTER = 4

    GENDER_CHOICES = (
        (GENDER_MALE, 'Male'),
        (GENDER_FEMALE, "Female"),
        (GENDER_ALIEN, "Alien"),
        (GENDER_FICTIONAL_CHARACTER, "Fictional character"),
    )

    name = models.CharField(max_length=255, null=False, blank=False)
    age = models.IntegerField()
    gender = models.PositiveSmallIntegerField(choices=GENDER_CHOICES, blank=True)
    course = models.ManyToManyField(Group, blank=True)
    email = models.EmailField(max_length=40, blank=True, null=True)

    class Meta:
        unique_together = ('name', 'email')

    def __str__(self):
        return self.name


# ContactUs Model for user feedback:
class ContactUs(models.Model):

    name = models.CharField(max_length=255)
    email = models.EmailField()
    tittle = models.CharField(max_length=255)
    message = models.TextField()

    def __str__(self):
        return f"{self.name} - {self.tittle}"

    def save(self, *args, **kwargs):
        super(ContactUs, self).save(*args, **kwargs)
        send_contact_us_email.delay(self.name, self.email, self.tittle, self.message)


class Logger(models.Model):
    path = models.CharField(max_length=255)
    method = models.CharField(max_length=255)
    log_time = models.DateTimeField(default=None)
    execution_time = models.FloatField()

    def __str__(self):
        return f'{self.path} -> {self.method}, {self.log_time}'


class ExchangeCurrency(models.Model):
    source = models.CharField(max_length=255)
    dollar = models.CharField(max_length=25, null=True)
    euro = models.CharField(max_length=25, null=True)
    ruble = models.CharField(max_length=25, null=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Source: {self.source}, Date: {self.date}'

django_school/core/forms.py
from django import forms
from core.models import Group, Teacher, Student, ContactUs


# Group form
class GroupForm(forms.Form):
    course = forms.CharField(max_length=255)
    group_lead = forms.ModelMultipleChoiceField(queryset=Teacher.objects.all())

    def save(self):
        group_lead = self.cleaned_data.pop('group_lead')
        group = Group.objects.create(
            **self.cleaned_data
        )
        group.group_lead.set(group_lead)

    def update_save(self, pk):
        group_lead = self.cleaned_data.pop('group_lead')
        group = Group.objects.get(id=pk)
        group.course = self.cleaned_data['course']
        group.group_lead.set(group_lead)
        group.save()


# Student form:
    # class StudentForm(forms.Form):
    #     name = forms.CharField(max_length=255)
    #     age = forms.IntegerField()
    #     gender = forms.PositiveSmallIntegerField()
    #     course = forms.ModelMultipleChoiceField(queryset=Group.objects.all())
    #     email = forms.EmailField(max_length=40)
    #
    #     def save(self):
    #         course = self.cleaned_data.pop('course')
    #         student = Student.objects.create(
    #             **self.cleaned_data
    #         )
    #         student.course.set(course)

# Student form with Model Usage
class StudentForm(forms.ModelForm):

    class Meta:
        model = Student
        fields = "__all__"  # Use: exclude = (<field>) - if need to exclude the required field
        widgets = {
            'gender': forms.widgets.RadioSelect(),
            'course': forms.widgets.CheckboxSelectMultiple()
        }


# Contact us form:
class ContactUsForm(forms.Form):
    name = forms.CharField(max_length=255)
    email = forms.EmailField()
    tittle = forms.CharField(max_length=255)
    message = forms.CharField(widget=forms.widgets.Textarea)

    def save(self):
        ContactUs.objects.create(**self.cleaned_data)

django_school/core/views.py
# standard imports
from django.shortcuts import render, redirect
from django.urls.base import reverse_lazy
from django.db.models.aggregates import Count, Avg, Max, Min
from django.views.generic.base import View, TemplateView
from django.views.generic import CreateView, FormView, UpdateView  # Views for useful work with Forms
from django.http import HttpResponse
import csv
# core app imports
from core.models import Group, Teacher, Student
from core.forms import GroupForm, StudentForm, ContactUsForm


# Create Group view:
class GroupView(TemplateView):
    template_name = 'group.html'

    def get_context_data(self, **kwargs):
        context = super(GroupView, self).get_context_data(**kwargs)
        groups = Group.objects.annotate(stq=Count('student'), stavg=Avg('student__age'),
                                        stmax=Max('student__age'),
                                        stmin=Min('student__age')).prefetch_related('group_lead')
        context['groups'] = groups
        return context


# Create Test view for :
class TestView(TemplateView):
    template_name = 'test.html'

    def get_context_data(self, **kwargs):
        context = super(TestView, self).get_context_data(**kwargs)
        context['lst'] = [0, 34, 98, 45, 39, 86, 44, 30, 45, 4]
        return context


# Create Teacher view:
class TeacherView(TemplateView):
    template_name = 'teachers.html'

    def get_context_data(self, **kwargs):
        context = super(TeacherView, self).get_context_data(**kwargs)
        context['teachers'] = Teacher.objects.all()
        return context


# TemplateViews for add new Group and Student:
# AddGroupView for Group model via TemplateView(and FormView):
# class AddGroupView(FormView):
#     template_name = 'add_update_group.html'
#     form_class = GroupForm
#     success_url = '/'
#
#     def form_valid(self, form):
#         form.save()
#         return super(AddGroupView, self).form_valid(form)


class AddGroupView(TemplateView):
    template_name = 'add_update_group.html'

    def get_context_data(self, **kwargs):
        context = super(AddGroupView, self).get_context_data(**kwargs)
        context['form'] = GroupForm()
        return context

    def post(self, request):
        form = GroupForm(data=request.POST, files=request.FILES)  # files=request.FILES for images(probably in Future)
        if form.is_valid():
            form.save()
            return redirect('/')
        context = self.get_context_data()
        context['form'] = form
        return self.render_to_response(context)


# AddStudentView for Student Model via CreateView(and TemplateView):
# class AddStudentView(TemplateView):
#     template_name = 'add_update_student.html'
#
#     def get_context_data(self, **kwargs):
#         context = super(AddStudentView, self).get_context_data(**kwargs)
#         context['form'] = StudentForm()
#         return context
#
#     def post(self, request):
#         form = StudentForm(data=request.POST, files=request.FILES)
#         if form.is_valid():
#             form.save()
#             return redirect('/')
#         context = self.get_context_data()
#         context['form'] = form
#         return self.render_to_response(context)


class AddStudentView(CreateView):
    template_name = 'add_update_student.html'
    success_url = reverse_lazy('index')
    model = Student
    form_class = StudentForm


# TemplateViews for update existing Group and Student:
# UpdateGroupView for Group model via FormView:
class UpdateGroupView(FormView):
    template_name = 'add_update_group.html'
    form_class = GroupForm
    success_url = reverse_lazy('index')

    def get_initial(self):
        name = Group.objects.get(id=self.kwargs['pk']).course
        return {'course': name}

    def form_valid(self, form):
        # group = Group.objects.get(id=self.kwargs['pk'])
        # group.course = form.cleaned_data['course']
        # group.group_lead.set(form.cleaned_data['group_lead'])
        pk = self.request.path.split('/')[-2]
        form.update_save(pk)
        return super(UpdateGroupView, self).form_valid(form)


# UpdateStudentView for Student Model via UpdateView:
class UpdateStudentView(UpdateView):
    template_name = 'add_update_student.html'
    success_url = reverse_lazy('index')
    model = Student
    form_class = StudentForm


# ContactUsView for user feedback:
class ContactUsView(FormView):
    template_name = "contact_us.html"
    form_class = ContactUsForm
    success_url = reverse_lazy('contact_us_done')

    def form_valid(self, form):
        form.save()
        return super(ContactUsView, self).form_valid(form)


# Students to CSV:
class ExportStudentsCSV(View):

    def get(self, request):
        queryset = Student.objects.all().prefetch_related('course')
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="students.csv"'
        writer = csv.writer(response)
        writer.writerow(['ID', 'Name', 'Email', 'Age', 'Course'])
        for student in queryset:
            writer.writerow([student.id, student.name, student.email, str(student.age),
                             ', '.join([student.course for student in student.course.all()])])
        return response

django_school/core/templates/add_update_group.html
{% extends "base.html" %}
{% load custom_tags %}
{% load bootstrap_tags %}

{% block content %}
<h1 align="right" style="font-size: 100%">{% now "SHORT_DATETIME_FORMAT" %}</h1>
<div class="container">
    <form method="post" enctype="multipart/form-data">{% csrf_token %} {# enctype="multipart/form-data" is for Images #}
            {{ form|as_bootstrap_inline }}
        <button type="submit" class="btn btn-primary">Add/edit group</button>
    </form>
</div>
{% endblock content %}

django_school/core/templates/add_update_student.html
{% extends "base.html" %}
{% load custom_tags %}
{% load bootstrap_tags %}

{% block content %}
<h1 align="right" style="font-size: 100%">{% now "SHORT_DATETIME_FORMAT" %}</h1>
<div class="container">
    <form method="post" enctype="multipart/form-data">{% csrf_token %}
        {{ form|as_bootstrap_horizontal }}
        <button type="submit" class="btn btn-primary">Add/edit Student</button>
    </form>
</div>
{% endblock content %}

django_school/core/templates/base.html
{% load bootstrap_tags %}
{% load static %}
<html>
    <head>
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
      {% block css %}{% endblock css %} {# example, what to do if you need extra #}
      <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
      {% block meta %}{% endblock meta %}
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <a class="navbar-brand" href="{% url 'index' %}">Django School</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'add_group' %}">Add Group</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'add_student' %}">Add Student</a>
              </li>
            </ul>
            <ul class="navbar-nav my-2">
              <li class="nav-item active">
                <a class="nav-link" href="/logout/">Logout</a>
              </li>
            </ul>
          </div>
        </nav>
        <div class="container">
          {% block content %}
          {% endblock content %}
        </div>
        <script src="{% static 'js/script.js'%}"></script>
         {% block js %}{% endblock js %} {# example, what to do if you need extra widgets #}
    </body>
</html>

django_school/core/templates/contact_us.html
{%  extends "base.html" %}
{% load bootstrap_tags %}

{% block content %}
<h3>Contact US</h3>
<form method="post" enctype="multipart/form-data">{% csrf_token %}
    {{ form|as_bootstrap_horizontal }}
    <button type="submit" class="btn btn-primary">Send message!</button>
</form>

{% endblock content %}

django_school/core/templates/contact_us_done.html
{%  extends "base.html" %}


{% block content %}

    <h1 class="text-center">Thanks for your message! We will respond soon!</h1>

{% endblock content %}

django_school/core/templates/group.html
{% extends "base.html" %}
{% load custom_tags %}

{% block content %}
<h1 align="right" style="font-size: 100%" id='date_time' >{% now "SHORT_DATETIME_FORMAT" %}</h1>
<table class="table">
    <tr>
        <th>Course</th>
        <th>Students quantity</th>
        <th>The youngest student age</th>
        <th>The oldest student age</th>
        <th>Average students age</th>
        <th>Group lead</th>

    </tr>
    {% for group in groups %}
    <tr style="background-color: {% cycle "lightgrey" "white" %}">
        <td>
             <a href="{% url 'update_group' group.id %}">{{ group.course }}</a>
        </td>{# Group name(trying django comments here) #}
        <td>{{ group.stq }}</td>{# field with count of students #}
        <td>{{ group.stmin }}</td>{# field for young student #}
        <td>{{ group.stmax }}</td>{# field for experienced student #}
        <td>{{ group.stavg }}</td>{# field for average group age #}
        <td>
             {% for lead in group.group_lead.all %}
                {{ lead.name}}
             {% endfor %}
        </td>
    {%  endfor %}
</table>
{% endblock content %}

django_school/core/templates/login.html
{% extends 'base.html' %}
{% load bootstrap_tags %}

{% block content %}
    <form method="post" enctype="multipart/form-data">{% csrf_token %}
        {{ form|as_bootstrap_horizontal }}
        <button type="submit" class="btn btn-primary">Login</button>
    </form>
{% endblock content %}

django_school/core/templates/teachers.html
{% extends "base.html" %}
{% load custom_tags %}

{% block content %}
<h1 align="right" style="font-size: 100%">{% now "SHORT_DATETIME_FORMAT" %}</h1>
{% for teacher in teachers %}
<div class="container"><br>
    <div class="card col-md-12">
      <div class="card-body">
        <p class="card-text">Teacher: <b>{{ teacher.name }}</b></p>
          {% for group in teacher.group_set.all %}
            <p>Group: <b></b>{{ group.course }}</p>
          {% endfor %}
      </div>
    </div>
</div>
{% endfor %}
{% endblock content %}

django_school/core/templates/test.html
{% extends "base.html" %}
{% load custom_tags %}

{% block content %}
<h1 align="right" style="font-size: 100%">{% now "SHORT_DATETIME_FORMAT" %}</h1>
<div class="container"><br>
<div class="card col-md-12">
  <div class="card-body">
    <h1 class="card-text">
      <br>
        <p>Words quantity in string: <b>{{ 'Hello, this - sentence is for testing ? my custom tag.'|words_quantity_in_string }}</b></p>
        <p>Even numbers from array ¯\_(ツ)_/¯: <b>{{ lst|even_numbers_from_array}}</b></p>
        <p>This month best of the best: <b>{% random_five_teachers %}</b></p>
  </div>
</div><br>
</div>
{% endblock content %}